
apiVersion: v1
kind: Namespace
metadata:
  name: dga-lab
---
apiVersion: v1
kind: Service
metadata: { name: gateway, namespace: dga-lab }
spec:
  selector: { app: gateway }
  ports: [{ port: 80, targetPort: 8080 }]
---
apiVersion: apps/v1
kind: Deployment
metadata: { name: gateway, namespace: dga-lab }
spec:
  replicas: 1
  selector: { matchLabels: { app: gateway } }
  template:
    metadata: { labels: { app: gateway } }
    spec:
      containers:
      - name: app
        image: ghcr.io/yourorg/gateway:latest
        ports: [{ containerPort: 8080 }]
---
apiVersion: apps/v1
kind: Deployment
metadata: { name: dga-detector, namespace: dga-lab }
spec:
  replicas: 1
  selector: { matchLabels: { app: dga-detector } }
  template:
    metadata: { labels: { app: dga-detector } }
    spec:
      containers:
      - name: model
        image: ghcr.io/yourorg/dga-detector:latest
        ports: [{ containerPort: 8501 }]
---
apiVersion: v1
kind: Service
metadata: { name: dga-detector, namespace: dga-lab }
spec:
  selector: { app: dga-detector }
  ports: [{ port: 8501, targetPort: 8501 }]
